on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel

name: lint

jobs:
  linter:
    name: SuperLinter 🦸‍♀️
    uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@main
