---
name: Man Pages 📃

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel

jobs:
  roxygen:
    name: Roxygen 🅾
    uses: insightsengineering/r.pkg.template/.github/workflows/roxygen.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
