---
name: Spelling 🆎

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel

jobs:
  spelling:
    name: Spell Check 🆎
    uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@main
