---
name: Style 🎽

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel

jobs:
  style:
    name: Style Check 👗
    uses: insightsengineering/r.pkg.template/.github/workflows/style.yaml@main
